Deep Learning system are often trained on **very large datasets.**

Tensorflow make easy:
* Data API
* TF Transform
* TFRecord
* TF Datasets

# TF Dataset

In [1]:
import tensorflow as tf
from tensorflow import keras

In [29]:
sample_data = [11, 22, 33, 44, 55, 66, 77, 88]
dataset = tf.data.Dataset.from_tensor_slices(sample_data)
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [30]:
for item in dataset:
    # print(item)
    print(item.numpy())

11
22
33
44
55
66
77
88


## Filter data

In [31]:
# Filter data
dataset = dataset.filter(lambda sample:sample>33)
for item in dataset:
    print(item)

tf.Tensor(44, shape=(), dtype=int32)
tf.Tensor(55, shape=(), dtype=int32)
tf.Tensor(66, shape=(), dtype=int32)
tf.Tensor(77, shape=(), dtype=int32)
tf.Tensor(88, shape=(), dtype=int32)


## Data transformations

In [32]:
# Data transformations
# dataset = dataset.repeat(3) # duplicate data
# dataset = dataset.batch(7) # group data. drop_remax
dataset = dataset.repeat(3).batch(7)
dataset

<BatchDataset shapes: (None,), types: tf.int32>

In [33]:
for item in dataset:
    print(item)

tf.Tensor([44 55 66 77 88 44 55], shape=(7,), dtype=int32)
tf.Tensor([66 77 88 44 55 66 77], shape=(7,), dtype=int32)
tf.Tensor([88], shape=(1,), dtype=int32)


## Custom transformation

In [35]:
# Custom transformation on Each Sample
dataset = dataset.unbatch() # ungroup data
dataset

<_UnbatchDataset shapes: (), types: tf.int32>

### Sysntax 1 (only for simple transform)
Note: num_paralled_calls = #threads